import Head from 'next/head';
import { useQuery } from "@apollo/client";
import Link from 'next/link';
import type { SchemaProduct } from '../schema/schema';
import { GET_PRODUCTS } from '../lib/apollo-client';
import { Card } from '../components/Card/Card';


export default function Home() {
  const query = useQuery(GET_PRODUCTS)
  
if(query.data === undefined) return <h1>Weit a moment</h1>
else{
  const {products} = query.data;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='my-12'>
        <h1 className='font-bold text-3xl my-5'>Products</h1>
        <div className='grid grid-cols-3 gap-10'>
          {products.map((product: SchemaProduct, i: number) => <Card key={i} data={product}/>)}
        </div>
      </div>
    </div>
  )
}
}

