import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useQuery } from "@apollo/client";
import Link from 'next/link';
import type { SchemaProduct } from '../schema/schema';
import { GET_PRODUCTS } from '../lib/apollo-client';

export default function Home() {
  const query = useQuery(GET_PRODUCTS)
  
if(query.data === undefined) return <h1>Weit a moment</h1>
else{
  const {products} = query.data;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome</h1>
      <ul>
      {products.map((product: SchemaProduct, i: number) => <Link key={i} href={`product/${product.slug}`}><li>{product.name} | Price: {product.price}</li></Link>)}
      </ul>
    </div>
  )
}
}

